#!/usr/bin/env ansible-playbook -i inventories

- name: Configure LAMP Ubuntu - Apache2 - MariaDb Server - Php7-Fpm
  hosts: demo
  sudo: True
  vars:

  vars_files:
    - group_vars/demo/apache2.yml
    - group_vars/demo/php7-fpm.yml
    - group_vars/demo/mariadb.yml
    - group_vars/demo/contents.yml
  roles:
        - mariadb
        - apache2
        - php7-fpm
        # - xdebug
        # - ntp
        - contents
  tasks:


  handlers:

    - name: restart apache2
      service: name=apache2 state=restarted

    - name: restart php-fpm
      service: name={{php_fpm_binary_name}} state=restarted