apt_cache_valid_time: 86400
ip_whitelist:
  - "{{ lookup('pipe', 'curl -4 -s https://api.ipify.org') }}"
www_root: /var/www
www_root_ssh: /var/www/.ssh
web_user: www-data
web_group: www-data
default_timezone: Europe/Madrid
http_port: 80


# php.ini settings
php_memory_limit: 512M
php_max_execution_time: 60
php_post_max_size: 100M
php_upload_max_filesize: 100M
php_display_errors: On
php_display_startup_errors: On
php_html_errors: On
php_date_timezone: Europe/Madrid